# Generated by Django 5.0 on 2025-09-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
