# Generated by Django 5.0 on 2025-09-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_gpa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gpa",
            field=models.CharField(max_length=20),
        ),
    ]
