# Generated by Django 5.0 on 2025-10-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_education_public_profile_email_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_visible',
            field=models.BooleanField(default=True),
        ),
    ]
