# Generated by Django 5.0 on 2025-11-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_profile_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_public",
            field=models.BooleanField(default=True),
        ),
    ]
