# Generated by Django 5.0 on 2025-09-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="post",
            new_name="job",
        ),
        migrations.AlterField(
            model_name="application",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
