# Generated by Django 5.0 on 2025-09-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('recruiters', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.post'),
        ),
        migrations.AlterField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
