# Generated by Django 5.0 on 2025-09-27 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("recruiters", "0002_alter_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="job",
        ),
        migrations.AddField(
            model_name="application",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="recruiters.post",
            ),
        ),
    ]
