# Generated by Django 5.0 on 2025-09-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_post_application_job_alter_application_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
