# Generated by Django 5.2.7 on 2025-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_visa_sponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
