# Generated by Django 5.2.7 on 2025-10-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_lat_job_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='lng',
        ),
    ]
