# Generated by Django 5.0 on 2025-09-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
