# Generated by Django 5.0 on 2025-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0002_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visa_sponsorship",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
    ]
