# Generated by Django 5.2.7 on 2025-10-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_post_visa_sponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
