# Generated by Django 5.0 on 2025-10-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
